### ISSUE TITLE
Facebook Research

### ISSUE THREAD

**Issue by jl4282** [jl4282/ModestWear#2]
How do you login with Facebook?

**Comment by katiekroik** [comment]
I found the basic instructions here:
Login with **FB**: https://developers.facebook.com/docs/facebook-login/web
- Need Facebook App ID
- Then get the code (example at the link above)
- Gets ID, email, and name

Login with **Google** : https://developers.google.com/identity/protocols/OAuth2WebServer
- Works with PHP, Python, Ruby, and **HTTP/REST**
- Sends a query of string params to the Google Authorization Server (response_type, client_id, redirect_uri, scope, state, access_type, etc...)
- There's code at the link above, but it looks like it handles it differently than the FB API. 

How do we want to handle this? Do we want either FB, Google, or our own login? Or just two of those options? Personally, I'm routing for FB or our own, because it gets handled much more similarly (I think) but we still need to integrate them.
